### PR TITLE
feat(katalog,minio-ha):update minio/minio and minio/mc

### PR DESCRIPTION
**Pull request by g-iannelli**
minio/minio -> RELEASE.2024-10-13T13-34-11Z
minio/mc -> RELEASE.2024-10-08T09-37-26Z

### CODE REVIEW

**Review by ralgozino — COMMENTED** [review]
are there no changes to the manifests?

**Review by nutellinoit — COMMENTED** [review]
Same question as @ralgozino

**Comment by g-iannelli** [comment]
> are there no changes to the manifests?

The only change it might make sense to consider is due to this PR https://github.com/minio/minio/pull/20547

**Review by ralgozino — APPROVED** [review]
lgtm

**Pull request merged**
