### PR TITLE
Fix path for kube-state-metrics dashboards

### PR DESCRIPTION
**Pull request by sbruzzese902**
Hi 👋  During an activity we spotted a wrong link in kube-state-metrics and fixed it. The initial `.` breaks the links between dashboards, for example from the`cluster` dashboard if you click on a namespace for details, you get an error because it tries to go to `<GRAFANA_URL>./d/<DASHBOARD>`

Many thanks to @giusepperotella who spotted and fixed the issue.

### CODE REVIEW

**Comment by ralgozino** [comment]
I can't replicate the issue locally, it works for me with a port-forward and also using an ingress. Tested using version 1.14.1 of the module

https://user-images.githubusercontent.com/6362698/172201596-72ee7ea0-579e-4dcf-8b47-e3d826efc57e.mov

.

**Comment by giusepperotella** [comment]
Hi @ralgozino , I found the problem with version 1.13.0 of the module.

**Comment by ralgozino** [comment]
Hi @giusepperotella! thanks for the info.
I tested this also with monitoring 1.13.0 and is working also. Do you happen to have the ingress definition that you used at hand so I can test it?

Thanks!

**Comment by giusepperotella** [comment]
Hi @ralgozino , we encountered the problem both through ingress nginx and through port-forward.
The definition of the ingress is as follows:
`---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/appName: "Grafana"
    forecastle.stakater.com/icon: "https://github.com/stakater/ForecastleIcons/raw/master/grafana.png"
  namespace: monitoring
  name: grafana
spec:
  rules:
    - host: grafana.fury.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port: 
                  number: 3000`

**Comment by ralgozino** [comment]
I tried to replicate the issue with your ingress definition, port-forward using Chrome, Firefox and Safari. It always works for me, even with version 1.13.0.

Can I ask you for detailed instructions on how to replicate the issue, please?

Thanks!

**Comment by giusepperotella** [comment]
hi @ralgozino , I have reviewed the video and the dashboard you are using is not the one on which we encountered the problem. The dashboard on which we encounter the problem is Kubernetes / Compute Resources / Cluster.
I checked and I also have the same problem with the v1.14.2 version of the module.

**Review by ralgozino — APPROVED** [review]

**Review by lnovara — APPROVED** [review]
LGTM! :shipit:

**Pull request merged**
