### PR TITLE
Adds compatibility matrix structure

### PR DESCRIPTION
**Pull request by angelbarrera92**
Hi team!

Adds compatibility matrix with information about current status. This is the first compatibility matrix we deploy so, review it carefully and suggestion are always welcomed!

Current status are recovered from drone pipelines!

Thanks!

### CODE REVIEW

**Comment by lnovara** [comment]
Shouldn't `fury-kubernetes-monitoring` be compatible also with v1.14.x?

Is there anything failing in CI for v1.14.x?

**Comment by angelbarrera92** [comment]
> Shouldn't `fury-kubernetes-monitoring` be compatible also with v1.14.x?
> 
> Is there anything failing in CI for v1.14.x?
Hi @lnovara 

We did not test it in the pipeline against 1.14 version. This is something that i want to change in upcoming commits/PRs.

So, the 1.14 column does not have information because we did not have automated tests. We can consider mark it as stable if someone has installed it in a 1.14 cluster. But with the data i have, it's considered "untested" in 1.14 and tested in 1.15 ;)

**Comment by lnovara** [comment]
@angelbarrera92 understood, we do have v1.14.x cluster running `fury-kubernetes-monitoring` but I agree with you that the compatibility matrix needs to be CI-driven.

**Comment by ralgozino** [comment]
Just out of curiosity, by "Current status are recovered from drone pipelines!" do you mean automatically?

**Comment by angelbarrera92** [comment]
> Just out of curiosity, by "Current status are recovered from drone pipelines!" do you mean automatically?

Not now...
By the moment, i was digging in drone pipelines looking for the correct pipeline and setting the result in the markdown table.

So, first step, make it working in multiple k8s versions. Then, automate as much as possible to get the markdown table written as pipeline output.

**Pull request merged**
