### PR TITLE
[HOTFIX] prometheus operated and alertmanager operated labels

### LINKED ISSUE #83: [BUG] - Prometheus service is rendered incorrectly with kustomize
https://github.com/sighupio/fury-kubernetes-monitoring/blob/54c827bb85783fa2e31a5f4cb15ed0fd690efa11/katalog/prometheus-operated/deploy.yml#L67

Since we are using common labels, the prometheus generated instance from prometheus operator is without required labels to be selected from the prometheus-k8s service

### PR DESCRIPTION
**Pull request by nutellinoit**
This PR fixes #83

What I did: added on the podMetadata field the same commonLabels we are adding on all resources

We should release an hotfixed version as soon as possible

### CODE REVIEW

**Comment by ralgozino** [comment]
For future reference. Here's the definition of `podMetadata` in the CRDs:
https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml#L3528
https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml#L4029

**Review by ralgozino — APPROVED** [review]
Looks good to me as a fix.

Did you evaluate using `labels` without changing the selector instead @nutellinoit ?
Ref: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/labels/

**Comment by nutellinoit** [comment]
> Did you evaluate using `labels` without changing the selector instead @nutellinoit ? Ref: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/labels/

No, i didn't, mainly because we are enforcing a check that commonLabels (with some labels) must be present on `kustomization.yaml` . 
Maybe we can change this behaviour to make the kustomize projects development easier

**Review by lnovara — APPROVED** [review]
LGTM. :shipit: 

Any reason not to use Kustomize's [TransformerConfigs](https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs/crd)?

**Comment by lnovara** [comment]
Yes, and, if my understanding is correct, the usage of a TransformerConfig would allow Kustomize's commonLabels to work as usual even on CRDs thus avoiding the need to manually patch the podMetadata field.

**Comment by ralgozino** [comment]
From my understanding the labels are used only by our fury-metadata to discover the modules deployed in the cluster (and other), i.e. we shouldn't need to update the selectors, so using `labels` instead of `commonLabels` would be better.

I created an issue on our Redmine to track this.

PS: IIRC annotations were discarded because one can easily ask K8s API filtering by label and not by annotations.

**Comment by lnovara** [comment]
OK, thanks for the explanation. 😄

**Comment by nutellinoit** [comment]
Changed the configuration using TransformerConfigs @lnovara

**Review by ralgozino — APPROVED** [review]

**Pull request merged**
