### PR TITLE
Adding namespace: monitoring on all thanos-components

### PR DESCRIPTION
**Pull request by nutellinoit**
Hi guys, opening this PR to address the use case: using handpicked components instead of our "recipe".

### CODE REVIEW

**Review by angelbarrera92 — APPROVED** [review]
LGTM!

**Review by lnovara — APPROVED** [review]
LGTM! :shipit:

**Comment by angelbarrera92** [comment]
Can someone resolve the conflicts? Thanks!

**Comment by lnovara** [comment]
@angelbarrera92 Rebased against current `master`.

**Comment by nutellinoit** [comment]
All conflicts fixed @angelbarrera92

**Pull request merged**
