### PR TITLE
chore ( #89): add RetentionSize

### PR DESCRIPTION
**Pull request by nohant**
as requested in the issue number 89, this will add the default RetentionSize as 80% of the default storage associated.

### CODE REVIEW

**Review by lnovara — APPROVED** [review]
Thank you @nohant! :shipit:

**Review by ralgozino — APPROVED** [review]
thank you @nohant!

**Comment by nohant** [comment]
may i merge directly @ralgozino?

**Review by ralgozino — CHANGES_REQUESTED** [review]
could you update the `katalog/prometheus-operated/README.md` file also please? thank you!

ps: sorry for the noise

**Review by ralgozino — APPROVED** [review]
lgtm

**Pull request merged**
