### PR TITLE
feat(grafana): added a custom Grafana dashboard

### PR DESCRIPTION
**Pull request by giusepperotella**
A new dashboard has been added on Grafana which allows you to have an overview of the status of the resources (deployment, daemonset, etc) present on the cluster.

### CODE REVIEW

**Comment by nutellinoit** [comment]
Hi Giuseppe, can you share a screenshot?

**Comment by giusepperotella** [comment]
> Hi @giusepperotella , can you share a screenshot?

Hi @nutellinoit , below are the screenshots of the developed dashboard:
Screenshot 2023-06-06 at 17 15 26

Screenshot 2023-06-06 at 17 16 01

Screenshot 2023-06-06 at 17 16 34

Screenshot 2023-06-06 at 17 16 52

**Review by ralgozino — CHANGES_REQUESTED** [review]
Great job @giusepperotella ! the dashboard is great.

Some minor suggestions and fixes:
1. Have you considered adding a row with Certificates information from the x509 exporter? Maybe you can copy some panels from the dedicated dashboard
2. The CPU usage and Memory usage panels don't show any values in my case, maybe I missed deploying some component? (I'm testing on a minikube cluster)
3. The "Node Status" row title doesn't reflect its content IMO. Opening it I don't see the node status at a glance (it is one of the columns of the table).
4. In my test, clicking the node name link in the "Node Status" table gives me a Not Found error (the Id for the node-exporter dashboard should be `nM8YQo_4k` instead of `JzmufwUVz` in the link)
5. I would change the variable name `role` to `node role` for clarity in the filters

**Comment by giusepperotella** [comment]
> Great job @giusepperotella ! the dashboard is great.
> 
> Some minor suggestions and fixes:
> 
> 1. Have you considered adding a row with Certificates information from the x509 exporter? Maybe you can copy some panels from the dedicated dashboard
> 2. The CPU usage and Memory usage panels don't show any values in my case, maybe I missed deploying some component? (I'm testing on a minikube cluster)
> 3. The "Node Status" row title doesn't reflect its content IMO. Opening it I don't see the node status at a glance (it is one of the columns of the table).
> 4. In my test, clicking the node name link in the "Node Status" table gives me a Not Found error (the Id for the node-exporter dashboard should be `nM8YQo_4k` instead of `JzmufwUVz` in the link)
> 5. I would change the variable name `role` to `node role` for clarity in the filters

Hi @ralgozino ,
thank you very much for the information provided.

1. I added the three gadgets: Total Certificates, Expired and Expiring within 7 days in the Cluster Overview section.
2. I checked on a cluster created with kubeadm and the gadgets are populated correctly. While using Minikube they are actually not populated. However, I noticed that, on Minikube, the other "Compute Resources" dashboards also do not have metrics. I carry out further checks
3. I renamed the section with Node Overview
4. I updated the ID as you indicated.
5. I updated the variable name as you indicated.

**Review by nutellinoit — APPROVED** [review]
LGTM for me

**Review by ralgozino — APPROVED** [review]
LGTM!

The only thing that I'm having doubts it's if the dashboard belongs to the `grafana` package or if it would be better to put it elsewhere (like in the `kubeadm-sm` package), we can always move it later though

**Pull request merged**
