### PR TITLE
[PROPOSAL] sighup-registry folder for image override

### PR DESCRIPTION
**Pull request by nutellinoit**
Hi team, we need to use the original image (quay, docker hub sources) for the fury modules in some use cases.

Me and @nikever were thinking about having a different folder for the "overridden images" modules and to use them only when needed.

What do you think about this?

### CODE REVIEW

**Comment by angelbarrera92** [comment]
🤔  Does this PR implement it? I don't see it

**Comment by nutellinoit** [comment]
> 🤔 Does this PR implement it? I don't see it

Yes, see this folder https://github.com/sighupio/fury-kubernetes-monitoring/tree/improve-kustomization-operated/katalog/sighup-registry

**Comment by angelbarrera92** [comment]
> > 🤔 Does this PR implement it? I don't see it
> 
> Yes, see this folder https://github.com/sighupio/fury-kubernetes-monitoring/tree/improve-kustomization-operated/katalog/sighup-registry

Maybe I didn't get the original PR description.
Or maybe the PR is not ready yet because I can only see two images (prom and alertmanager). What about the prometheus-operator, goldpinger and so on?

**Comment by nikever** [comment]
The main idea is to have an easy way to choose the docker images you want to use. 
I think we should default to the official images for the "public" and have a simple switch for us to enable our registry.

Moreover, it would be great if we can generalize this approach allowing any person to use their own registry.

Regarding 

> > > 🤔 Does this PR implement it? I don't see it
> > 
> > 
> > Yes, see this folder https://github.com/sighupio/fury-kubernetes-monitoring/tree/improve-kustomization-operated/katalog/sighup-registry
> 
> Maybe I didn't get the original PR description.
> Or maybe the PR is not ready yet because I can only see two images (prom and alertmanager). What about the prometheus-operator, goldpinger and so on?

The other images can be replaced using `newImage` as you did for `reg.sighup.io`.
The images in the PR can't be replaced with that approach since they are CRD.

**Comment by nutellinoit** [comment]
Yes @angelbarrera92 , this PR is not finished. We didn't do all of them, we did only a bunch of them as an example for the general idea

**Comment by angelbarrera92** [comment]
Ok!!

Understood the approach :)

I like the idea, Do you consider the other way round?
I mean, by default leave reg.sighup.io, then create a new "package"/dir named `upstream-registry` with the default/upstream versions of the container images.

This way we don't alter (again) the behaviour of the module.

**Pull request closed without merging**
